-- maia_owner_preferences_v1
-- O que muda e por quê: permite ao owner propor e confirmar preferências restritas de resposta.
-- Nada é ativado pela chamada da IA; a confirmação explícita usa uma RPC do servidor.
-- Código que depende desta migração: server/ownerPreferences.ts, server/rules.ts,
-- server/maiaImageTool.ts, server/codexMaiaMcp.ts, server/ownerRouter.ts.
-- Rollback: nova migração que revogue a RPC e remova as tabelas após desativar o recurso.

create table public.maia_owner_preference_proposals (
  id bigint generated by default as identity primary key,
  scope text not null check (scope in ('resposta', 'sugestoes', 'restricao')),
  instruction text not null check (char_length(btrim(instruction)) between 1 and 300),
  status text not null default 'pending' check (status in ('pending', 'activated', 'cancelled', 'expired')),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '10 minutes'),
  resolved_at timestamptz
);

create index maia_owner_preference_proposals_pending_idx
  on public.maia_owner_preference_proposals (expires_at)
  where status = 'pending';

create table public.maia_owner_preferences (
  id bigint generated by default as identity primary key,
  scope text not null check (scope in ('resposta', 'sugestoes', 'restricao')),
  instruction text not null check (char_length(btrim(instruction)) between 1 and 300),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index maia_owner_preferences_one_active_per_scope_idx
  on public.maia_owner_preferences (scope)
  where active;

alter table public.maia_owner_preference_proposals enable row level security;
alter table public.maia_owner_preferences enable row level security;

revoke all on public.maia_owner_preference_proposals from public, anon, authenticated;
revoke all on public.maia_owner_preferences from public, anon, authenticated;
grant select, insert, update on public.maia_owner_preference_proposals to service_role;
grant select, insert, update on public.maia_owner_preferences to service_role;
grant usage, select on sequence public.maia_owner_preference_proposals_id_seq to service_role;
grant usage, select on sequence public.maia_owner_preferences_id_seq to service_role;

create or replace function public.activate_owner_preference(p_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_proposal public.maia_owner_preference_proposals%rowtype;
begin
  select * into v_proposal
    from public.maia_owner_preference_proposals
    where id = p_id
    for update;

  if not found or v_proposal.status <> 'pending' then
    return false;
  end if;

  if v_proposal.expires_at <= now() then
    update public.maia_owner_preference_proposals
      set status = 'expired', resolved_at = now()
      where id = p_id;
    return false;
  end if;

  update public.maia_owner_preferences
    set active = false
    where scope = v_proposal.scope and active;

  insert into public.maia_owner_preferences(scope, instruction, active)
    values (v_proposal.scope, v_proposal.instruction, true);

  update public.maia_owner_preference_proposals
    set status = 'activated', resolved_at = now()
    where id = p_id;

  return true;
end;
$$;

revoke all on function public.activate_owner_preference(bigint) from public, anon, authenticated;
grant execute on function public.activate_owner_preference(bigint) to service_role;
